# Generated by Django 5.1.3 on 2025-06-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Ativo', 'ativo'), ('Inativo', 'inativo')], default='Ativo', max_length=15)),
            ],
        ),
    ]
