# Generated by Django 5.1.3 on 2024-12-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='matriculado',
            field=models.BooleanField(default=False),
        ),
    ]
