# Generated by Django 5.1.3 on 2024-12-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_cliente_matriculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='mensagem',
            field=models.TextField(max_length=500),
        ),
    ]
