# Generated by Django 5.1.3 on 2025-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_cliente_matriculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
